Logging: 
  IncludeScopes: false
  Debug:
    LogLevel: 
      Default: Information
      Fortune_Teller_Service: Debug
      Fortune_Teller_UI: Debug
      Pivotal: Debug
      Steeltoe: Debug
  Console:
    LogLevel: 
      Default: Information
      Fortune_Teller_Service: Debug
      Fortune_Teller_UI: Debug
      Pivotal: Debug
      Steeltoe: Debug
eureka:
  client:
    serviceUrl: http://localhost:8761/eureka/
    validate_certificates: false